//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NKMapTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_NKMAPTTYPE                  129
#define IDD_MYFILEDLG                   130
#define IDD_FILE_NEWTERRAIN             131
#define IDD_TOOL_VERTEX_EDIT            132
#define IDD_TOOL_TEXTURE_PAINT          133
#define IDD_TOOL_OBJECT_EDIT            134
#define IDD_TOOL_ATTMAP_EDIT            135
#define IDD_TOOL_LIGHT_EDIT             136
#define IDD_PROGRESSDLG                 137
#define IDD_TOOL_ATMOS_EDIT             138
#define IDD_TOOL_MAPMOVE                139
#define IDD_FILE_MERGE_MAPS             140
#define IDD_FILE_REMOVE_OBJS            141
#define IDB_FILE_NONEPREVIEW            145
#define IDB_TOOL_VERTEX_EDIT            146
#define IDB_TOOL_TEXTURE_PAINT          147
#define IDB_TOOL_OBJECT_EDIT            148
#define IDB_TOOL_LIGHT_EDIT             149
#define IDB_TOOL_ATTMAP_EDIT            150
#define IDB_TOOL_LAYER1                 151
#define IDB_TOOL_LAYER2                 152
#define IDB_TOOL_LAYER3                 153
#define IDB_TOOL_LAYER1_ON              154
#define IDB_TOOL_LAYER2_ON              155
#define IDB_TOOL_LAYER3_ON              156
#define IDB_TOOL_SHOW_ICON              157
#define IDB_TOOL_HIDE_ICON              158
#define IDB_TOOL_PENCIL                 159
#define IDB_TOOL_BRUSH                  160
#define IDB_TOOL_PAINT                  161
#define IDB_TOOL_ERASE                  162
#define IDB_TOOL_PAINT_ON               163
#define IDB_TOOL_ERASE_ON               164
#define IDB_TOOL_RAISE                  168
#define IDB_TOOL_LOWER                  169
#define IDB_TOOL_FLATTEN                170
#define IDB_TOOL_SMOOTH                 171
#define IDB_TOOL_RAISE_ON               172
#define IDB_TOOL_LOWER_ON               173
#define IDB_TOOL_FLATTEN_ON             174
#define IDB_TOOL_SMOOTH_ON              175
#define IDB_TOOL_TILE                   176
#define IDB_TOOL_VERTEX                 177
#define IDB_TOOL_TILE_ON                178
#define IDB_TOOL_VERTEX_ON              179
#define IDB_TOOL_RAISEALL               180
#define IDB_TOOL_LIGHT_CONTROL          181
#define IDB_TOOL_LOWERALL               182
#define IDB_TOOL_LIGHT_CONTROL_ON       183
#define IDB_NAKO_ICON                   184
#define IDB_TOOL_PAINT_S                185
#define IDB_TOOL_PAINT_ON_S             186
#define IDB_TOOL_ERASE_S                187
#define IDB_TOOL_ERASE_ON_S             188
#define IDB_TOOL_ATMOS_EDIT             189
#define IDB_TOOL_SELECT                 190
#define IDB_TOOL_SELECT_ON              191
#define IDB_TOOL_PLACE                  192
#define IDB_TOOL_PLACE_ON               193
#define IDB_TOOL_MOVE                   194
#define IDB_TOOL_MOVE_ON                195
#define IDB_TOOL_ROTATE                 196
#define IDB_TOOL_ROTATE_ON              197
#define IDB_TOOL_ALIGN                  198
#define IDB_TOOL_ARRAY                  199
#define IDB_TOOL_WATER                  200
#define IDB_TOOL_WAVE                   201
#define IDB_TOOL_WATER_ON               202
#define IDB_TOOL_WAVE_ON                203
#define IDC_FILE_PREVIEW                1001
#define IDC_FILE_PREVIEW_INFO           1002
#define IDC_NEWTERRAIN_NAME             1003
#define IDC_NEWTERRAIN_WHSEGMENT        1004
#define IDC_NEWTERRAIN_PATCHSIZE        1005
#define IDC_NEWTERRAIN_HEIGHTSCALE      1006
#define IDC_NEWTERRAIN_BASETEXNAME      1007
#define IDC_NEWTERRAIN_HMNAME           1008
#define IDC_NEWTERRAIN_OPENTEX          1009
#define IDC_NEWTERRAIN_OPENHM           1010
#define IDC_NEWTERRAIN_GENERATE         1011
#define IDC_TOOL_PAINT_LISTBOX          1016
#define IDC_TOOL_PAINT_NEW              1017
#define IDC_TOOL_PAINT_DELETE           1018
#define IDC_TOOL_PAINT_LAYER1           1019
#define IDC_TOOL_PAINT_LAYER2           1020
#define IDC_TOOL_PAINT_LAYER3           1021
#define IDC_TOOL_PAINT_SHOW_LAYER1      1022
#define IDC_TOOL_PAINT_SHOW_LAYER2      1023
#define IDC_TOOL_PAINT_SHOW_LAYER3      1024
#define IDC_TOOL_PAINT_FILTER           1025
#define IDC_TOOL_PAINT_TYPE_P           1026
#define IDC_TOOL_PAINT_TYPE_E           1027
#define IDC_TOOL_PAINT_TOOL_TYPE        1028
#define IDC_TOOL_PAINT_SIZE_EDIT        1029
#define IDC_TOOL_PAINT_SIZE_SLIDER      1030
#define IDC_TOOL_PAINT_STRENGTH_EDIT    1031
#define IDC_TOOL_PAINT_STRENGTH_SLIDER  1032
#define IDC_TOOL_PAINT_COLORBOX         1033
#define IDC_TOOL_OBJECT_LISTBOX         1041
#define IDC_TOOL_OBJECT_INDEX           1042
#define IDC_TOOL_OBJECT_TYPE            1043
#define IDC_TOOL_OBJECT_NAME            1044
#define IDC_TOOL_OBJECT_LOLO            1045
#define IDC_TOOL_OBJECT_OPENLOLO        1046
#define IDC_TOOL_OBJECT_INSERT          1047
#define IDC_TOOL_OBJECT_MODIFY          1048
#define IDC_TOOL_OBJECT_REMOVE          1049
#define IDC_TOOL_OBJECT_SELECT          1050
#define IDC_TOOL_OBJECT_PLACE           1051
#define IDC_TOOL_OBJECT_MOVE            1052
#define IDC_TOOL_OBJECT_ROTATE          1053
#define IDC_TOOL_OBJECT_X_EDIT          1054
#define IDC_TOOL_OBJECT_Y_EDIT          1055
#define IDC_TOOL_OBJECT_Z_EDIT          1056
#define IDC_TOOL_OBJECT_ROTATE_EDIT     1057
#define IDC_TOOL_OBJECT_RANDOM          1058
#define IDC_TOOL_OBJECT_NODEBOUND       1059
#define IDC_TOOL_OBJECT_OFFSET          1060
#define IDC_TOOL_OBJECT_COUNT           1061
#define IDC_TOOL_OBJECT_AXIS_X          1062
#define IDC_TOOL_OBJECT_AXIS_Y          1063
#define IDC_TOOL_OBJECT_AXIS_Z          1064
#define IDC_TOOL_OBJECT_ALIGN           1065
#define IDC_TOOL_OBJECT_ARRAY           1066
#define IDC_TOOL_VERTEX_NAME            1067
#define IDC_TOOL_VERTEX_SEGMENT         1068
#define IDC_TOOL_VERTEX_PATCHSIZE       1069
#define IDC_TOOL_VERTEX_HEIGHTSCALE     1070
#define IDC_TOOL_VERTEX_MINMAXHEIGHT    1071
#define IDC_TOOL_VERTEX_PATCHSIZE_MODIFY 1072
#define IDC_TOOL_VERTEX_HEIGHTSCALE_MODIFY 1073
#define IDC_TOOL_VERTEX_CONTROL_TILE    1074
#define IDC_TOOL_VERTEX_CONTROL_VERTEX  1075
#define IDC_TOOL_VERTEX_RAISE           1076
#define IDC_TOOL_VERTEX_LOWER           1077
#define IDC_TOOL_VERTEX_FLATTEN         1078
#define IDC_TOOL_VERTEX_SMOOTH          1079
#define IDC_TOOL_VERTEX_BRUSH_SIZE_EDIT 1080
#define IDC_TOOL_VERTEX_BRUSH_SIZE_SLIDER 1081
#define IDC_TOOL_VERTEX_BRUSH_STRENGTH_EDIT 1082
#define IDC_TOOL_VERTEX_BRUSH_STRENGTH_SLIDER 1083
#define IDC_TOOL_VERTEX_HEIGHTMAP_REAPPLY 1084
#define IDC_TOOL_VERTEX_HEIGHTMAP_EXPORT 1085
#define IDC_TOOL_VERTEX_RAISE_ENTIRE    1086
#define IDC_TOOL_VERTEX_LOWER_ENTIRE    1087
#define IDC_TOOL_VERTEX_OFFSET          1088
#define IDC_TOOL_LIGHT_TIME             1089
#define IDC_TOOL_LIGHT_DIRX             1090
#define IDC_TOOL_LIGHT_DIRY             1091
#define IDC_TOOL_LIGHT_DIRZ             1092
#define IDC_TOOL_LIGHT_LIGHTR_EDIT      1095
#define IDC_TOOL_LIGHT_LIGHTG_EDIT      1096
#define IDC_TOOL_LIGHT_LIGHTB_EDIT      1097
#define IDC_TOOL_LIGHT_AMBIENTR_EDIT    1098
#define IDC_TOOL_LIGHT_AMBIENTG_EDIT    1099
#define IDC_TOOL_LIGHT_AMBIENTB_EDIT    1100
#define IDC_TOOL_LIGHT_LIGHTCOLOR       1108
#define IDC_TOOL_LIGHT_AMBIENTCOLOR     1109
#define IDC_TOOL_LIGHT_DIRCONTROL       1113
#define IDC_PROGRESS_CTRL               1114
#define IDC_PROGRESS_TITLE              1115
#define IDC_PROGRESS_CONTENT            1116
#define IDC_TOOL_LIGHT_PAINT            1117
#define IDC_TOOL_LIGHT_ERASE            1118
#define IDC_FRAME                       0x045f
#define IDC_TOOL_LIGHT_SHADOWCOLOR      1120
#define IDC_TOOL_LIGHT_SHADOWR_EDIT     1121
#define IDC_TOOL_LIGHT_SHADOWG_EDIT     1122
#define IDC_TOOL_LIGHT_SHADOWB_EDIT     1123
#define IDC_TOOL_LIGHT_BRUSH_SIZE_EDIT  1124
#define IDC_TOOL_LIGHT_BRUSH_SIZE_SLIDER 1126
#define IDC_TOOL_LIGHT_BRUSH_STRENGTH_SLIDER 1127
#define IDC_TOOL_LIGHT_BRUSH_STRENGTH_EDIT 1128
#define IDC_TOOL_LIGHT_SHADOW_CURMAP    1129
#define IDC_TOOL_ATMOS_WATER_HEIGHT     1142
#define IDC_TOOL_ATMOS_WATER_BASE_TEXNAME 1143
#define IDC_TOOL_ATMOS_WATER_WAVE_TEXNAME 1144
#define IDC_TOOL_ATMOS_WATER_WAVE_TEXNAME2 1145
#define IDC_TOOL_ATMOS_WATER_BASE_TEXNAME_OPEN 1146
#define IDC_TOOL_ATMOS_WATER_WAVE_TEXNAME_OPEN 1147
#define IDC_TOOL_ATMOS_WATER_WAVE_TEXNAME_OPEN2 1148
#define IDC_TOOL_ATMOS_WATER_TYPE_BASE  1149
#define IDC_TOOL_ATMOS_WATER_TYPE_WAVE  1150
#define IDC_TOOL_ATMOS_WATER_EDIT_PAINT 1151
#define IDC_TOOL_ATMOS_WATER_EDIT_ERASE 1152
#define IDC_TOOL_ATMOS_WATER_GROUP      1153
#define IDC_TOOL_ATMOS_WATER_GROUP_ADD  1154
#define IDC_TOOL_ATMOS_WATER_GROUP_MODIFY 1155
#define IDC_TOOL_ATMOS_WATER_GROUP_REMOVE 1156
#define IDC_TOOL_ATMOS_WATER_GROUP_NAME 1157
#define IDC_TOOL_ATMOS_WATER_SEGMENT    1158
#define IDC_TOOL_ATMOS_WATER_OPACITY    1159
#define IDC_TOOL_ATMOS_WATER_PAINT_ALL  1160
#define IDC_TOOL_ATMOS_WATER_OPACITY_SPIN 1161
#define IDC_TOOL_ATMOS_WATER_SEGMENT_SPIN 1162
#define IDC_TOOL_ATMOS_WATER_PAINT_ALLWAVE 1163
#define IDC_TOOL_OBJECT_IMPORT          1177
#define IDC_TOOL_ATMOS_WATER_GUIDE_LINE 1178
#define IDC_TOOL_OBJECT_REFERENCE       1179
#define IDC_TOOL_MAPMOVE_TILE           1180
#define IDC_TOOL_MAPMOVE_WORLD          1181
#define IDC_TOOL_MAPMOVE_X              1182
#define IDC_TOOL_MAPMOVE_Z              1183
#define IDC_TOOL_LIGHT_SHADOW_IMPORT    1184
#define IDC_TOOL_LIGHT_SHADOW_EXPORT    1185
#define IDC_TOOL_ATTMAP_ABLETOWALK_COLOR 1186
#define IDC_TOOL_ATTMAP_UNABLETOWALK_COLOR 1187
#define IDC_TOOL_ATTMAP_WATER_COLOR     1188
#define IDC_TOOL_ATTMAP_INDOOR_COLOR    1189
#define IDC_TOOL_ATTMAP_INDOORBOX_COLOR 1190
#define IDC_TOOL_ATTMAP_OUTDOORBOX_COLOR 1191
#define IDC_TOOL_ATTMAP_ABLETOWALK      1192
#define IDC_TOOL_ATTMAP_UNABLETOWALK    1193
#define IDC_TOOL_ATTMAP_WATER           1194
#define IDC_TOOL_ATTMAP_INDOOR          1195
#define IDC_TOOL_ATTMAP_INDOORBOX       1196
#define IDC_TOOL_ATTMAP_OUTDOORBOX      1197
#define IDC_TOOL_ATTMAP_RANGE           1198
#define IDC_TOOL_ATTMAP_RANGE_SPIN      1199
#define IDC_TOOL_ATTMAP_GENERATE        1200
#define IDC_TOOL_ATTMAP_IMPORT          1201
#define IDC_TOOL_ATTMAP_EXPORT          1202
#define IDC_TOOL_PAINT_REPLACE          1203
#define IDC_MERGEMAP_NMF_NAME           1205
#define IDC_MERGEMAP_NOT_NAME           1206
#define IDC_MERGEMAP_NMF_OPEN           1207
#define IDC_MERGEMAP_NOT_OPEN           1208
#define IDC_MERGEMAP_REGION_SX          1209
#define IDC_MERGEMAP_REGION_EX          1210
#define IDC_MERGEMAP_REGION_SZ          1211
#define IDC_MERGEMAP_REGION_EZ          1212
#define IDC_MERGEMAP_MERGE              1213
#define IDC_TOOL_OBJECT_REMOVE_INREGION 1214
#define IDC_REMOVE_OBJECTS_SX           1215
#define IDC_REMOVE_OBJECTS_SZ           1216
#define IDC_REMOVE_OBJECTS_EX           1217
#define IDC_REMOVE_OBJECTS_EZ           1218
#define IDC_TOOL_LIGHT_DEFAULT          1219
#define IDC_REMOVE_OBJECTS              1220
#define IDC_CHECK_LOCALAXIS             1220
#define IDC_TOOL_ATTMAP_BRUSH_SIZE_EDIT 1223
#define IDC_TOOL_ATTMAP_BRUSH_SIZE_SLIDER 1224
#define ID_VIEW_TERRAIN                 32781
#define ID_VIEW_OBJECT                  32782
#define ID_VIEW_FOG                     32783
#define ID_VIEW_SKY                     32784
#define ID_VIEW_LIGHT                   32785
#define ID_VIEW_GRID_NONE               32786
#define ID_VIEW_GRID_SMALL              32787
#define ID_VIEW_GRID_MEDIUM             32788
#define ID_VIEW_GRID_LARGE              32789
#define ID_TOOL_ATTRIBUTE_EDIT_ICON     32791
#define ID_TOOL_ATTRIBUTE_EDIT          32792
#define ID_TOOL_LIGHT_EDIT              32797
#define ID_TOOL_LIGHT_EDIT_ICON         32798
#define ID_VIEW_CHARACTER               32799
#define ID_TOOL_VERTEX_EDIT             32800
#define ID_TOOL_VERTEX_EDIT_ICON        32801
#define ID_TOOL_TEXTURE_PAINT           32802
#define ID_TOOL_TEXTURE_PAINT_ICON      32803
#define ID_TOOL_OBJECT_EDIT             32804
#define ID_TOOL_OBJECT_EDIT_ICON        32805
#define ID_TOOL_ATMOSPHERE_EDIT         32806
#define ID_TOOL_ATMOS_EDIT_ICON         32807
#define ID_TOOL_MAPMOVE                 32808
#define ID_TOOL_MAPMOVE_ICON            32809
#define ID_FILE_OPEN_GAME_MAP           32810
#define ID_FILE_SAVE_GAME_MAP           32811
#define ID_FILE_MERGE_MAP               32812
#define ID_HOTKEY_Q                     32813
#define ID_HOTKEY_W                     32814
#define ID_HOTKEY_E                     32815
#define ID_HOTKEY_R                     32816
#define ID_CAMERA_SPEED1X               32817
#define ID_CAMERA_SPEED2X               32818
#define ID_CAMERA_SPEED4X               32819
#define ID_CAMERA_SPEED8X               32820
#define ID_CAMERA_OBSERVE               32821
#define ID_CAMERA_FLY                   32822
#define ID_VIEW_WATER                   32823
#define ID_CAMERA_SPEED10X              32824
#define ID_VIEW_ATTR_MAP                32825
#define ID_CAMERA_UNLIMIT               32826
#define ID_INDICATOR_FPS                61204
#define ID_INDICATOR_TRIS               61205
#define ID_INDICATOR_SIZE               61206
#define ID_INDICATOR_COPYRIGHT          61207
#define ID_INDICATOR_TIME               61208
#define ID_INDICATOR_COORD              61209

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
